resources:
- name: concourse-bitbucket-pullrequest-resource
  type: git
  source:
    uri: https://github.com/emerald-squad/concourse-bitbucket-pullrequest-resource.git
    branch: 'master'

- name: docker-hub
  type: docker-image
  source:
    repository: emeraldsquad/concourse-bitbucket-pullrequest-resource
    username: ((docker-hub-username))
    password: ((docker-hub-password))

jobs:
- name: publish
  plan:
  - get: concourse-bitbucket-pullrequest-resource
    trigger: true
  - task: get-version
    file: concourse-bitbucket-pullrequest-resource/ci/tasks/get-version.yml
  - put: docker-hub
    params:
      build: concourse-bitbucket-pullrequest-resource
      tag: version/version
      tag_as_latest: true
